//DROP TABLE BOOKS;
create table BOOKS
( ID bigint generated by default as identity,
 BOOK_NO varchar(30), 
 BOOK_PRICE INT not null, 
 COUNT INT not null, 
 DEPT_NAME varchar(30) ,
 PUBLISHER varchar(50), 
 REG_RSN varchar(255),
 REGISTER_NM varchar(30), 
 TITLE varchar(300),
 DATE DATE,
 STATUS varchar(30),
 primary key (id) 
);
create table MEMBERS
( ID bigint generated by default as identity,
  USER_NAME varchar(30),
  PASSWORD varchar(500),
  NAME varchar(100),
  DEPT_NAME varchar(50),
  AUTHORITY  varchar(50),
  primary key (id)
)
