//DROP TABLE BOOKS;
create table BOOKS
( ID bigint generated by default as identity,
 BOOK_NO varchar(30), 
 BOOK_PRICE INT not null, 
 COUNT INT not null, 
 DEPT_NAME varchar(30) ,
 PUBLISHER varchar(50), 
 REG_RSN varchar(255), 
 REGISTER_NM varchar(30), 
 TITLE varchar(300),
 primary key (id) 
);
